models:
    openllama:
        # model_name: OpenLLAMAZHPEFTModel
        model_name: OpenLLAMAModel
        agent_name: DeepSpeedAgent
        stage1_train_dataset: SupervisedDataset
        test_dataset: SelfInstructTestDataset

# ========= Global configuration ========== #
root_dir: /home/johnlan/nanoChatGPT
version: 0
logging_step: 5
save_interval: 0.5
# ========= Global configuration ========== #
